import java.util.Scanner;
import java.io.StringWriter;
import java.io.PrintWriter;

class Do {
    private static void doPrint() {
        System.out.println("Generated by the doPrint method.");
    }
    
    public static int doNumber() {
        System.out.println("1");
    }
}

public class Stuff {
    public static void main(String[] args) {
        // double dlb = 0.0;
        // StringWriter stw = new StringWriter();
        // PrintWriter ptw = new PrintWriter(stw);
        // Scanner scnr = new Scanner(System.in);
        
        // System.out.print("Enter a value: ");
        // dlb = scnr.nextDouble();
        // while (dlb != 0.0) {
            // ptw.printf("%.0f ", dlb);
            // System.out.print("Enter a value(0 to exit): ");
            // dlb = scnr.nextDouble();
        // }
        
        // System.out.print(stw.toString());
        
        Do myDo = new Do();
        
    }
}